compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
conda_forge_output_validation: true
provider: {linux_aarch64: default, linux_ppc64le: default}
build_platform:
  linux_ppc64le: linux_64
test_on_native_only: true
